### ISSUE TITLE
spansy: decide to what extent to validate

### ISSUE THREAD

**Issue by sinui0** [tlsnotary/tlsn-utils#23]
@themighty1 suggested in #21 that we perform validation of parsed HTTP messages to check that we don't have duplicate `Content-Type` headers. This poses a larger question as to what extent `spansy` validates the data it parses. Is it an HTTP type library? Or just a dumb span parser?

My view at the moment is that it should stay as a dumb parser as much as possible. Types exported by `spansy` should only be considered syntactically valid (parse-able).

**Comment by themighty1** [comment]
I agree that there's no need to do any validation in `spansy` **as long as** there exists a way to tell the user what headers are present in the HTTP message. 
Currently there is only `Request::headers_with_name()` but we need something like `Request::all_header_names()` and let the user decide what to do when there are duplicate header names.

**Comment by th4s** [comment]
I agree that `spansy` should only do parsing/spanning. @themighty1 `headers_with_name` returns an iterator so the user will have to handle the case if there are duplicate headers with the same name. Or do I misunderstand?

**Comment by themighty1** [comment]
@th4s , I was suggesting that the user should be able to check for duplicate header names without knowing in advance what the duplicate header name is. 
Anyway, my point is now moot since I noticed that `Request::headers` are `pub`. That should be good enough to give access to all headers.
I think this issue can be closed @sinui0
